import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localfont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });

const editor =localfont({
  src:[{
    path :"../../public/fonts/PPEditorialNew-Italic-BF644b214fb0c0a.otf",
    weight:"300",
  }],
  variable:"--fonts-editor",
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${editor.variable}`}>
      <body>
        {children}
      </body>
    </html>
  );
}
