import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localfont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const bigger = localfont({
  src:[{
    path: "../../public/fonts/BiggerDisplay.otf",
    weight: "400",
  }],
  variable: "--font-bigger",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${bigger.variable}`}>{children}</body>
    </html>
  );
}
